### ISSUE TITLE
Aide crash

### ISSUE THREAD

**Issue by rekmolly** [TrinityDevelopers/Space-Plus-PE#2]
In file SpadeItemSP.cpp AIDE crash on line 16

**Comment by rekmolly** [comment]
I hid her comment but the game still crash :(

**Comment by TrinityDevelopers** [comment]
I'll look into it!  Thanks for telling me.

**Comment by rekmolly** [comment]
The new version takes off when I go to the world :(

**Comment by TrinityDevelopers** [comment]
Yes I know about that.  It is related to crafting recipes... I will hopefully fix this today.

**Comment by rekmolly** [comment]
You are about to add blocks and the planet as Galacticraft?

**Comment by TrinityDevelopers** [comment]
Yes those are planned.  After I fix the recipes I will add more items and blocks.  Then I will add entities and planets.

**Comment by rekmolly** [comment]
I'll look forward to it :)
And why do you use such a complex system of adding items ?

**Comment by TrinityDevelopers** [comment]
What's so complex?  I just did it like that so they would work best.

**Comment by rekmolly** [comment]
I just can not understand how to add items 0.12. And your code is too complex and do not want to just copy it.
Just when I try to add a block or item with Tile.h/Item.h the game will crash

**Comment by TrinityDevelopers** [comment]
You can copy it.  I sort of wrote it to be a template for others.

**Comment by TrinityDevelopers** [comment]
Just like rename the classes and stuff

**Comment by rekmolly** [comment]
Forgive my poor English . In the past I just did not write as much code to add only thing I simply plugs Item.h and to create a class object and initialize it after.And in just 0.12 a game crash.

And if you need assistance to be translated into other languages ​​addon ? I could do a translation into Russian :)
