### ISSUE TITLE
MCPE Crash

### ISSUE THREAD

**Issue by bia5** [TrinityDevelopers/Space-Plus-PE#3]
I dont know completly why, but i always get a crash when i try to create (and/or) load a world.

**Comment by rekmolly** [comment]
I advise you to remove the code recipes. Because of them the game crashes.

**Comment by bia5** [comment]
Thank you, never thought about that. ;)

**Comment by TrinityDevelopers** [comment]
Yes that is a big issue.  I really want to fix them, but I am really busy with school.  Will hopefully get to them soon!

**Comment by Khristian-kun** [comment]
i can fix it, my version has crafting recipes without bugs!
