### ISSUE TITLE
Undate to 0.13.0

### ISSUE THREAD

**Issue by razvanfilea** [TrinityDevelopers/Space-Plus-PE#5]
Please update to 0.13.0

**Comment by Khristian-kun** [comment]
its hard to do, but ill try to update to 0.13

**Comment by razvanfilea** [comment]
I hope that this helps you: I did a basic block repository You should use the files in jni/MCPE
https://github.com/Razvan145/BlockExample-MCPE

**Comment by Khristian-kun** [comment]
i know
